name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Run tests with Pytest
      run: pytest

    - name: Lint with Ruff
      run: ruff check src/

    - name: Start Flask App on Port 8000
      run: |
        nohup python src/main.py &
        sleep 5

    - name: Check if Flask App is Running
      run: curl -f http://127.0.0.1:8000
